### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by Ivanwangcy** [facebooknuclide/hyperclick#26] opened 2017-07-21 06:58 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.0-beta4 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.11.6
**Thrown From**: [hyperclick](https://github.com/facebooknuclide/hyperclick) package 0.1.2

### Stack Trace

Uncaught TypeError: Cannot read property 'length' of undefined

```
At /Applications/Atom Beta.app/Contents/Resources/app/src/text-editor-component.js:2266

TypeError: Cannot read property 'length' of undefined
    at TextEditorComponent.screenPositionForPixelPosition (/Applications/Atom Beta.app/Contents/Resources/app/src/text-editor-component.js:2266:33)
    at TextEditorComponent.screenPositionForMouseEvent (/Applications/Atom Beta.app/Contents/Resources/app/src/text-editor-component.js:1858:23)
    at t.default._getMousePositionAsBufferPosition (/packages/hyperclick/index.js:1:161291)
    at t.default._isMouseAtLastWordRange (/packages/hyperclick/index.js:1:161913)
    at t.default._onMouseMove (/packages/hyperclick/index.js:1:159183)
```

### Commands

```
     -1:03.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-when-scrolling.seti-icons.seti-animate)
     -0:50.1.0 vim-mode-plus:delete (input.hidden-input)
     -0:48.8.0 vim-mode-plus:inner-subword (input.hidden-input)
  8x -0:48.3.0 vim-mode-plus:delete (input.hidden-input)
     -0:42.9.0 vim-mode-plus:set-count-1 (input.hidden-input)
     -0:41.6.0 vim-mode-plus:repeat (input.hidden-input)
     -0:38.1.0 vim-mode-plus:activate-insert-mode (input.hidden-input)
  3x -0:37.5.0 core:backspace (input.hidden-input)
  2x -0:22.3.0 core:save (input.hidden-input)
     -0:20.3.0 docblockr:parse-enter (input.hidden-input)
     -0:20.3.0 editor:newline (input.hidden-input)
     -0:13.2.0 docblockr:parse-enter (input.hidden-input)
     -0:13.2.0 editor:newline (input.hidden-input)
```

### Non-Core Packages

```
activate-power-mode 2.1.0 
atom-material-syntax 1.0.6 
atom-material-syntax-dark 1.0.0 
atom-material-ui 2.0.4 
atom-ternjs 0.18.3 
atom-wx 0.1.1 
autocomplete-emojis 2.5.0 
busy-signal 1.4.3 
color-picker 2.2.5 
css-snippets 1.1.0 
docblockr 0.11.0 
editorconfig 2.2.2 
emmet 2.4.3 
ex-mode 0.15.0 
file-icons 2.1.9 
haskell-grammar 0.4.0 
highlight-selected 0.13.1 
hyperclick 0.1.2 
intentions 1.1.2 
js-hyperclick 1.11.0 
language-babel 2.67.1 
language-graphql 0.9.0 
language-ini 1.19.0 
language-lua 0.9.11 
language-ocaml 1.9.5 
language-rust 0.4.11 
language-swift 0.5.0 
language-thrift 1.0.2 
language-vue 0.23.0 
linter 2.2.0 
linter-eslint 8.2.1 
linter-js-standard 3.9.1 
linter-scss-lint 3.1.0 
linter-ui-default 1.6.3 
MagicPython 1.0.10 
merge-conflicts 1.4.5 
minimap 4.29.0 
minimap-pigments 0.2.2 
monokai 0.24.0 
nuclide 0.241.0 
nuclide-format-js 0.0.36 
pigments 0.39.1 
react-native-components 0.1.1 
react-native-snippets 0.3.0 
react-snippets 0.8.0 
set-syntax 0.3.2 
seti-syntax 1.1.3 
seti-ui 1.9.0 
sort-lines 0.14.0 
standardjs-snippets 2.6.0 
Stylus 3.1.1 
sync-settings 0.8.2 
tag 0.5.0 
toggle-quotes 1.0.1 
tool-bar 1.1.0 
vim-mode-plus 0.94.0 
wxapp 0.1.0 
```

**Comment by tjfryan** [comment] 2017-07-21 17:43
Hey, thanks for testing Nuclide with the Atom Beta!  I think it may be the case that the changes to the implementation of the textbuffer in Atom 1.19 could be causing your issue.  See if you are unable to reproduce with Atom 1.18 and if so, report the regression to atom: https://github.com/atom/atom/issues

**Comment by hansonw** [comment] 2017-07-21 23:50
Dupe of #24

**Closed as completed by hansonw** 2017-07-21 23:50 UTC
