### ISSUE TITLE
Deprecated selector in `hyperclick\styles\hyperclick.less`

### ISSUE THREAD

**Issue by CdricZhang** [facebooknuclide/hyperclick#7] opened 2017-01-13 02:52 UTC
In `hyperclick\styles\hyperclick.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `atom-text-editor::shadow .editor-contents--private .highlight.hyperclick > .region` => `atom-text-editor.editor .editor-contents--private .highlight.hyperclick > .region`

* `atom-text-editor:not([mini]).hyperclick::shadow .editor-contents--private` => `atom-text-editor:not([mini]).hyperclick.editor .editor-contents--private`

* `atom-text-editor:not([mini]).hyperclick-loading::shadow .editor-contents--private` => `atom-text-editor:not([mini]).hyperclick-loading.editor .editor-contents--private`

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by joshlewis** [comment] 2017-01-13 15:31
This is a duplicate of #5.

**Comment by zertosh** [comment] 2017-01-21 01:24
I've published hyperclick@v0.0.40 which fixes this issue.

**Closed as completed by zertosh** 2017-01-21 01:24 UTC
