### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by fcrisciani** [facebooknuclide/hyperclick#24] opened 2017-07-14 16:18 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.0-beta3 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.5
**Thrown From**: [hyperclick](https://github.com/facebooknuclide/hyperclick) package 0.1.2

### Stack Trace

Uncaught TypeError: Cannot read property 'length' of undefined

```
At /Applications/Atom Beta.app/Contents/Resources/app/src/text-editor-component.js:2263

TypeError: Cannot read property 'length' of undefined
    at TextEditorComponent.screenPositionForPixelPosition (/Applications/Atom Beta.app/Contents/Resources/app/src/text-editor-component.js:2263:33)
    at TextEditorComponent.screenPositionForMouseEvent (/Applications/Atom Beta.app/Contents/Resources/app/src/text-editor-component.js:1855:23)
    at t.default._getMousePositionAsBufferPosition (/packages/hyperclick/index.js:1:161291)
    at t.default._isMouseAtLastWordRange (/packages/hyperclick/index.js:1:161913)
    at t.default._onMouseMove (/packages/hyperclick/index.js:1:159183)
```

### Commands

```
     -0:38.3.0 fuzzy-finder:toggle-file-finder (input.hidden-input)
     -0:35.7.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.30.3 
auto-update-packages 1.0.1 
busy-signal 1.4.3 
file-icons 2.1.8 
git-blame 1.1.1 
git-history 3.3.0 
git-time-machine 1.5.9 
go-debug 1.5.0 
go-outline 0.6.6 
go-plus 5.5.5 
go-signature-statusbar 1.2.1 
highlight-selected 0.13.1 
hyperclick 0.1.2 
intentions 1.1.2 
language-protobuf 0.7.1 
last-cursor-position 0.9.2 
linter 2.2.0 
linter-ui-default 1.6.2 
maximize-panes 0.2.0 
minimap 4.28.3 
minimap-cursorline 0.2.0 
minimap-git-diff 4.3.1 
minimap-highlight-selected 4.6.1 
minimap-linter 2.0.1 
minimap-selection 4.4.0 
minimap-split-diff 0.3.7 
persistent-undo 1.2.0 
project-manager 3.3.5 
split-diff 1.4.3 
sync-settings 0.8.2 
```

**Comment by rightparen** [comment] 2017-07-14 17:11
@fcrisciani your package list indicates Nuclide is not installed, and the callstack looks like an Atom issue.  Consider reporting this issue at https://github.com/atom/atom/issues.

**Comment by fcrisciani** [comment] 2017-07-14 17:16
@rightparen ok thanks

**Comment by hansonw** [comment] 2017-07-14 17:36
@rightparen this is actually the hyperclick repo :D I think this particular issue is caused by split-diff actually

**Comment by rightparen** [comment] 2017-07-14 17:56
Oops!  Thanks @hansonw and sorry @fcrisciani for the confusion.

**Comment by fcrisciani** [comment] 2017-07-14 18:01
@rightparen no prob, my bad I did not really look at the trace, I just opened it from atom and sometimes it happened that goes into the wrong repo

**Comment by hansonw** [comment] 2017-07-14 18:33
@fcrisciani can you disable the split-diff package to see if that fixes it? This is a basic text editor API so some other package may be interfering with it

**Comment by hansonw** [comment] 2017-07-24 19:31
This is fixed in beta5! https://github.com/atom/atom/pull/15051

**Closed as completed by hansonw** 2017-07-24 19:31 UTC
